language: php
php:
    - 5.3.2
    - 5.3
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update

script: phpunit

services:
  - couchdb

notifications:
    email:
        - maxim@xiag.ch