language: php
php:
    - 5.5
    - 5.6
    - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer install --prefer-source

script: phpunit --coverage-text
